[workspace.package]
version = "2.6.0-beta.1"
repository = "https://github.com/arkedge/c2a-tlmcmddb"
readme = "README.md"

[workspace]
resolver = "2"

members = [
  "tlmcmddb",
  "tlmcmddb-csv",
  "tlmcmddb-cli",
]

[workspace.dependencies]
tlmcmddb = "2.6.0-beta.1"
tlmcmddb-csv = "2.6.0-beta.1"
