name: Rust

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

env:
  CARGO_INCREMENTAL: 0
  # renovate: datasource=github-releases depName=EmbarkStudios/cargo-about
  CARGO_ABOUT_VERSION: 0.6.4

jobs:
  rust:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Get Rust toolchain
        id: toolchain
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # v1
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          components: clippy, rustfmt

      - name: cache dependencies
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8

      - name: install cargo-about
        run: |
          cargo install cargo-about --locked --version ${{ env.CARGO_ABOUT_VERSION }}

      - name: reviewdog / clippy
        if: github.event_name == 'pull_request'
        uses: sksat/action-clippy@87e08e0c289f2654fe702b0aaf88c2f1027a3e57 # v1.1.1
        with:
          reporter: github-pr-review
      - name: reviewdog / clippy
        if: github.event_name == 'push'
        uses: sksat/action-clippy@87e08e0c289f2654fe702b0aaf88c2f1027a3e57 # v1.1.1
        with:
          reporter: github-check

      - name: format
        run: |
          cargo fmt --all -- --check

      - name: unit test
        run: |
          cargo test
