name: validate renovate

on:
  pull_request:
    paths:
      - 'renovate.json'
      - '.github/workflows/validate-renovate.yml'

jobs:
  validate-renovate:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0

      - name: install
        run: |
          npm install -g renovate
      - name: validate
        run: |
          renovate-config-validator
